### ISSUE TITLE
Consider set screw for shaft into rotor adaptor plate

### ISSUE THREAD

**Issue by matthew-reynolds** [q-pup/q-pup-mechanical#28]
> mild concern about the shaft deforming over time and introducing extra slop over time

Agreed, we could maybe put a set-screw into the rotor adaptor plate and an allen-key-sized hole in the motor casing? Or perhaps we should just see how it is for now.

_Originally posted by @matthew-reynolds in https://github.com/q-pup/q-pup-mechanical/issues/24#issuecomment-1008352812_

**Comment by wmmc88** [comment]
I think for now just keep it as is, but keep it on our watchlist of stuff that may need iteration

**Comment by matthew-reynolds** [comment]
Based on how the hex shaft was fitting in the torque test rotor adaptor, I'm going to close this for now. It can be re-opened if needed later.
