### ISSUE TITLE
Retolerance motor module parts to new spec

### ISSUE THREAD

**Issue by wmmc88** [q-pup/q-pup-mechanical#33]
Set tolerances to some number between 0.075 and 0.1mm

Using the [v2 makers muse tolerance guage](https://www.makersmuse.com/clearance-and-tolerance-3d-printer-gauge)

![image](https://user-images.githubusercontent.com/16629657/150067220-9ffaad05-ff52-49e8-ad56-13cc6a0354f3.png)

**Comment by wraftus** [comment]
## Features with tolerance
- [ ] hex bore in [`rotor_adapter`](https://github.com/q-pup/q-pup-mechanical/blob/main/q-pup/motor_module/rotor_adaptor.SLDPRT)
- [ ] hex bore in [`cam_a`](https://github.com/q-pup/q-pup-mechanical/blob/main/q-pup/motor_module/cam_a.SLDPRT)
- [ ] hex bore in [`cam_b`](https://github.com/q-pup/q-pup-mechanical/blob/main/q-pup/motor_module/cam_b.SLDPRT)
- [ ] bearing bore and pitch radius in [`cycloidal_disk`](https://github.com/q-pup/q-pup-mechanical/blob/main/q-pup/motor_module/cycloidal_disk.SLDPRT)
- [ ]  bearing bore in [`motor_casing`](https://github.com/q-pup/q-pup-mechanical/blob/main/q-pup/motor_module/motor_casing.SLDPRT)
- [ ] pin bore and in [`output_shaft`](https://github.com/q-pup/q-pup-mechanical/blob/main/q-pup/motor_module/output_shaft.SLDPRT)
- [ ] ??? in [`rotor_adapter_ring`](https://github.com/q-pup/q-pup-mechanical/blob/main/q-pup/motor_module/rotor_adaptor_ring.SLDPRT)

**Comment by matthew-reynolds** [comment]
We shouldn't need a list of things, if you just update the tolerances file everything will update

**Comment by wmmc88** [comment]
I think @wraftus mightve wanted to do a sanity check that those things are all toleranced
